### ISSUE TITLE
移动端钱包无法切换账户

### ISSUE THREAD

**Issue by luciaaaa4455** [Phala-Network/token-bridge-ui#6]
我在移动端钱包里切换了账户，但是在phala钱包里还没有切换，地址栏显示的还是上一个地址。点击地址栏弹出切换地址列表，点击新的地址没有变化。
用的tp钱包。

**Comment by kingsleydon** [comment]
TP 切换账户会刷新页面，之后 App 会默认展示上一次的地址，等待几秒读取到新的账户后会自动切换
